---
- name: Install Nomad and configure client
  hosts: localhost
  become: yes
  vars:
    nomad_version: "1.2.3"  # Specify the version of Nomad to install
  tasks:
    - name: Install required packages
      apt:
        name: ["apt-transport-https", "ca-certificates", "curl", "gnupg-agent", "software-properties-common"]
        state: present

    - name: Add HashiCorp GPG key
      apt_key:
        url: "https://apt.releases.hashicorp.com/gpg"
        state: present

    - name: Add HashiCorp APT repository
      apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
        state: present

    - name: Install Nomad
      apt:
        name: "nomad={{ nomad_version }}"
        state: present

    - name: Create Nomad data directory
      file:
        path: "/var/lib/nomad"
        state: directory
        mode: "0755"

    - name: Enable Docker driver in Nomad client configuration
      blockinfile:
        path: "/etc/nomad/nomad-client.hcl"
        block: |
          client {
            enabled = true
            servers = ["34.31.88.86:4647"]
            options {
              "driver.docker.enabled" = "true"
              "plugin.docker.config.image" = "docker:19.03.12"
              "plugin.docker.config.privileged" = "true"
              "plugin.docker.config.volumes.enabled" = "true"
              "plugin.docker.config.network_mode" = "bridge"
            }
          }

    - name: Start Nomad client service
      service:
        name: nomad
        state: started
        enabled: yes
