---
- name: Install Nomad and configure client
  hosts: localhost
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name: ["apt-transport-https", "ca-certificates", "curl", "gnupg-agent", "software-properties-common","docker.io","docker-compose"]
        state: present

    - name: Create Nomad data directory
      file:
        path: "/var/lib/nomad"
        state: directory
        mode: "0777"
    - name: Start Nomad client service
      shell:
        cmd: nomad agent -config /home/prapatidar/client.hcl
