---
- name: Install Nomad and configure client
  hosts: localhost
  become: yes
  tasks:
    - name: Install required packages
      apt:
        name: ["apt-transport-https", "ca-certificates", "curl", "gnupg-agent", "software-properties-common"]
        state: present

    - name: Create Nomad data directory
      file:
        path: "/var/lib/nomad"
        state: directory
        mode: "0755"
    - name: Start Nomad client service
      service:
        name: nomad
        state: started
        enabled: yes
        args: "-config=/home/prapatidar/playbook/client.hcl"
