---
- name: Install Nomad and configure client
  hosts: localhost
  become: yes
  gather_facts: yes
  tasks:
    - name: update apt-cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Install required packages
      apt:
        name: ["apt-transport-https", "ca-certificates", "curl", "gnupg-agent", "software-properties-common","docker.io","docker-compose"]
        state: present

    - name: Create Nomad data directory
      file:
        path: "/var/lib/nomad"
        state: directory
        mode: "0777"
    - name: Update the software package repository
      apt:
        update_cache: yes
    - name: Install dependencies
      package:
        name: ["curl", "net-tools", "unzip"]
        state: latest
    - name: Install consul
      unarchive:
        src: https://releases.hashicorp.com/consul/1.1.0/consul_1.1.0_linux_amd64.zip
        dest: /usr/local/bin
        remote_src: yes
    - name: Verify consul installation
      shell: "consul --version"
      register: consul_version
    - name: Create consul user
      user:
        name: consul
    - name: Create Consul /var directory
      file:
          path: /var/consul
          state: directory
          owner: consul
          group: consul
          mode: 0755
